
modLoader="javafml" 
loaderVersion="[36,)" 
license="MIT"
[[mods]]
modId="tranzistio" 
version="${file.jarVersion}" 
displayName="Tranzistio" #mandatory
logoFile="examplemod.png" #optional
description='''
Mod by Tranzistor54.
'''

[[dependencies.tranzistio]] 
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.tranzistio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
